service: canada-commons-app

provider:
  name: aws
  runtime: nodejs12.x
  region: ca-central-1
  stage: dev
  profile: commons
  vpc:
    securityGroupIds:
      - sg-0a41933a78e15ee98
    subnetIds:
      - subnet-adc794c5
      - subnet-33593649
      - subnet-34ec046b

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  graphql:
    handler: src/lambda.handler
    timeout: 20
    events:
      - http:
          path: api
          method: post
          cors: true
      - http:
          path: api
          method: get
          cors: true
  update-bills:
    description: Update bills for LEGISINFO website
    handler: src/cron/update-bills.handler
    events:
      - schedule: rate(1 day)

custom:
  tscpaths:
    buildPath: .build
  dotenv:
    include:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEGISINFO_URL
      - SUMMARY_URL
      - AWS_IAM_ACCESS_KEY_ID
      - AWS_IAM_SECRET_ACCESS_KEY
