service: canada-commons-app

provider:
  name: aws
  runtime: nodejs12.x
  region: ca-central-1
  stage: dev

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  tscpaths:
    buildPath: .build
  dotenv:
    include:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - AWS_REGION
