service: my-express-application

provider:
  name: aws
  runtime: nodejs12.18.1
  stage: dev
  region: ca-central-1

functions:
  graphql:
    handler: server.handler
    events:
      - http:
          path: api
          method: post
          cors: true
